version: '3.7'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: dicaninja
      POSTGRES_USER: dicaninja
      POSTGRES_PASSWORD: Age14rjy
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
