name: Deploy .NET Core app to Azure VM

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install .NET 7
      run: |
        wget -q https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
        sudo dpkg -i packages-microsoft-prod.deb
        sudo apt-get update
        sudo apt-get install -y apt-transport-https
        sudo apt-get update
        sudo apt-get install -y dotnet-sdk-7.0
    - name: Install dependencies
      run: dotnet restore
    - name: Run unit tests
      run: dotnet test
    - name: Build app
      run: dotnet build --configuration Release
    - name: Upload app to Azure VM
      uses: actions/upload-artifact@v1
      with:
        artifact: bin/Release/netcoreapp7.0
        target-path: /home/azureuser/app
    - name: Deploy app to Azure VM
      uses: actions/ssh-action@v1
      with:
        host: ${{ secrets.VM_IP }}
        username: ${{ secrets.VM_USER }}
        password: ${{ secrets.VM_PASSWORD }}
        script: |
          sudo mv /home/azureuser/app/* /var/ygor/DicaNinjaAPI
          sudo systemctl restart apache2
          cd /var/www/html
          pm2 start "dotnet DicaNinja.API.dll" --name backend
